config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  resources :wheels

  get '*unmatched_route', to: 'application#not_found'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :wheels
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter filtering_params
      results = self.active
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :wheel

  has_attached_file :data, styles: {medium: '300x300#'}
  validates_attachment :data, presence: true,
                       content_type: {content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']},
                       size: {in: 0..3.megabytes}
end

app/models/side.rb
class Side < ActiveRecord::Base
end

app/models/wheel.rb
class Wheel < ActiveRecord::Base
  include Filterable

  belongs_to :brand
  belongs_to :side
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  delegate :name, to: :brand, prefix: true

  scope :active, ->{includes :brand, :images}
  scope :brand,  ->(brand_id){where brand_id: brand_id}
  scope :radius, ->(radius){where radius: radius}
  scope :side,   ->(side_id){where side_id: side_id}
  scope :width,  ->(width){where width: width}
  scope :height, ->(height){where height: height}

  def full_name
    "#{brand_name} #{name} #{title}"
  end

  def avatar
    images.first.data.url(:medium)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def index

  end
end

app/controllers/wheels_controller.rb
class WheelsController < ApplicationController
  def index
    @brands = Brand.pluck(:name, :id)
    @sides = Side.pluck(:name, :id)
    @wheels = Wheel.filter filtering_params
  end

  private

  def filtering_params
    params.slice :brand, :radius, :side, :width, :height
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neverstop</title>
  <meta name="description" content='мотопокрышки черкассы'>
  <meta name='keywords' content='мотопокрышки,мотопокрышки черкассы,моторезина,моторезина бу черкассы,моторезина бу украина'>
  <meta name='author' content='Sasha Stadnik'>
  <meta http-equiv='content-type' content='text/html; charset=UTF-8'>
  <meta http-equiv='refresh' content='30'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css' %>

  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body id='app'>
  <div class='container-fluid'>
    <div id='main' class='row'>
      <div id='left_navbar' class='col-xs-4 col-sm-4 col-md-3 col-lg-2'>
        <%= render 'layouts/box/left_navbar'%>
      </div>
      <div id='box' class='col-xs-8 col-sm-8 col-md-9 col-lg-10'>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/box/_left_navbar.html.haml
= form_tag wheels_path, method: 'get', id: 'filter' do
  .form-group
    = select_tag 'brand', options_for_select(@brands, params[:brand]), prompt: 'Виробник', class: 'selectpicker'
  .form-group
    = select_tag 'radius', options_for_select([14,17, 18, 21], params[:radius]), prompt: 'Радіус', class: 'selectpicker'
  .form-group
    = select_tag 'side', options_for_select(@sides, params[:side]), prompt: 'Вісь застосування', class: 'selectpicker'
  .form-group
    = select_tag 'width', options_for_select([150, 160, 170, 180, 190], params[:width]), prompt: 'Ширина', class: 'selectpicker'
  .form-group
    = select_tag 'height', options_for_select([70, 80, 90], params[:height]), prompt: 'Висота', class: 'selectpicker'
  .form-group.search
    .btn-group.bootstrap-select
      = submit_tag 'Пошук', class: 'btn btn-danger col-xs-12'
    .btn-group.bootstrap-select
      = button_tag 'Очистити', id: 'clear', data: {behavior: 'LeftNavbar'}, class: 'btn btn-danger col-xs-12'

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neverstop</title>
  <meta name="description" content='мотопокрышки черкассы'>
  <meta name='keywords' content='мотопокрышки,мотопокрышки черкассы,моторезина,моторезина бу черкассы,моторезина бу украина'>
  <meta name='author' content='Sasha Stadnik'>
  <meta http-equiv='content-type' content='text/html; charset=UTF-8'>
  <meta http-equiv='refresh' content='30'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='welcome'>

<%= yield %>
</body>
</html>

app/views/welcome/index.html.haml
.container-fluid
  .row
    .col-xs-12.tc
      .img
        = image_tag 'finish-logo-2.png'
      .img
        = image_tag 'Cherckasy22.png'
    .col-xs-12.tc.buy
      = link_to 'Шопінг', wheels_path, class: 'btn btn-danger btnf'

app/views/wheels/_wheel.html.haml
.col-xs-3
  .wheel
    .wheel-img
      = link_to '#', title: wheel.full_name do
        .fade-container
          .mask
          = image_tag wheel.avatar, class: 'image'
    .footer
      .row
        .col-xs-12.name{title: wheel.brand_name}= wheel.brand_name
        .col-xs-12.name{title: wheel.title}= wheel.title
      .row.end
        .col-xs-12.tc= "#{wheel.price} грн"
        .col-xs-12.tc= link_to 'Купить', '#', class: 'btn btn-danger'

app/views/wheels/_wheels_collection.html.haml
- step = 0

- while wheels[step]
  .row
    - 4.times do |i|
      - if wheels[i + step].nil?
        - break
      = render partial: 'wheel', locals: {wheel: wheels[i + step]}
    - step += 4

app/views/wheels/index.html.haml
= render partial: 'wheels_collection', locals: {wheels: @wheels}